Hotel-App/Controllers/AboutController.cs
using Hotel_App.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_App.Controllers
{
    public class AboutController : Controller
    {
        private AppDbContext _dbContext;

        public AboutController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hotel-App/Controllers/ContactController.cs
using Hotel_App.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_App.Controllers
{
    public class ContactController : Controller
    {
        private AppDbContext _dbContext;

        public ContactController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hotel-App/Controllers/HotelController.cs
using Hotel_App.Data;
using Hotel_App.Models.ViewModels;
using Hotel_App.Models.ViewModels.Hotel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_App.Controllers
{
    public class HotelController : Controller
    {
        private AppDbContext _dbContext;

        public HotelController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var hotels = await _dbContext.Hotels.ToListAsync();
            var hotelList = new List<HotelViewModel>();

            foreach (var hotel in hotels)
            {
                hotelList.Add(new HotelViewModel
                {
                    Name = hotel.Name,
                    Description = hotel.Description,
                    Image = hotel.Image
                });
            }
            return View(hotelList);
        }
    }
}

Hotel-App/Controllers/ServiceController.cs
using Hotel_App.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_App.Controllers
{
    public class ServiceController : Controller
    {

        private AppDbContext _dbContext;

        public ServiceController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hotel-App/Views/Shared/Components/Header/Default.cshtml
<!-- top bar -->
<div class="hotel-top-bar">
    <div class="container">
        <div class="hotel-left-side">
            <!-- logo -->
            <a href="index.html" class="hotel-logo-frame" style="width: 50px;">
                <img src="~/img/hotellogo.png" alt="logo">
            </a>
            <!-- logo end -->
        </div>
        <div class="hotel-right-side">
            <!-- menu -->
            <div class="hotel-menu">
                <nav>
                    <ul>
                        <li class="current-item">
                            <a asp-action="Index" asp-controller="Home">Ana Səhifə</a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="About">Haqqımızda</a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Hotel">Hotellər</a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Room">Otaqlar</a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Service">Xidmətlərimiz</a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Contact">Əlaqə</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- menu end -->
            <!-- action button -->
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-action="Logout" asp-controller="Account" class="hotel-btn"><img src="~/img/icons/bookmark.svg" alt="icon">
                    Çıxış
                </a>
            }
            else
            {
                <a asp-action="Login" asp-controller="Account" class="hotel-btn"><img src="~/img/icons/bookmark.svg" alt="icon">Giriş</a>
            }
            <!-- action button end -->
        </div>
        <!-- menu button -->
        <div class="hotel-menu-btn"><span></span></div>
        <!-- menu button end -->
    </div>
</div>
<!-- top bar end -->